Dependencies and Renaming
NTIA/scos-usrp pull request #14
Opened 2022-04-11 20:38 UTC by jhazentia

This PR includes the following changes:
- Update pre-commit dependencies
- Rename radio to sigan or Signal Analyzer
- Change minimum Python to 3.7
- Use pip-tools for managing dependencies
- Use broad range of version numbers in requirements to reduce dependency conflicts
- Use scos-actions 1.0.0
- Change USRPLocation get_lan_long() to get_location(), return height

Propose to tag release as version 0.1.0

2022-04-12 16:51 UTC, dboulware requested changes
Looks good. Just a couple minor comments. See in-line comments.

2022-04-12 16:51 UTC, dboulware commented on README.md
> +scos-sensor. It does not include dependencies already in scos-sensor.
This is not true.

2022-04-12 16:51 UTC, dboulware commented on scos_usrp/discover/__init__.py
> +yaml_actions, yaml_test_actions = init(sigan=sigan, yaml_dir=ACTION_DEFINITIONS_DIR)
Just in case this should add gps = gps in the init call

2022-04-12 21:33 UTC, jhazentia commented on README.md
> +scos-sensor. It does not include dependencies already in scos-sensor.
Fixed. Good catch, thanks!

2022-04-15 18:28 UTC, dboulware approved these changes

2022-04-15 18:29 UTC, merged